repos:
  # Hooks that are run everywhere
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.4
    hooks:
      - id: biome-format
  # Hooks that are run for scripts
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(src|tests)/
      - id: ruff-format
        files: ^(src|tests)/