name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.10"
          - os: ubuntu-latest
            python: "3.11"
          - os: ubuntu-latest
            python: "3.12"
          - os: macos-latest
            python: "3.12"

    name: ${{ matrix.name }} Python ${{ matrix.python }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          pip install tox
          pip install ${{ matrix.pip-flags }} ".[optional-dependencies.dev,optional-dependencies.test,optional-dependencies.external,optional-dependencies.docs,optional-dependencies.embedding]"
          pip install wandb omegaconf
      - name: Test
        run: |
          tox -e py-${{ matrix.python }}
        env:
          PYTEST_ADDOPTS: -vv -n 2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: theislab/cellflow